source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

abstract_target 'ikemen' do
  pod "※ikemen", :path => "../"

  target 'ikemen_Example' do
    inherit! :complete
    platform :ios, '8.0'

    target 'ikemen_Tests' do
      inherit! :search_paths

      pod 'Quick'
      pod 'Nimble'
    end
  end

  target 'ikemen-Example-osx' do
    inherit! :complete
    platform :osx, '10.11'
  end
end

