source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

def import_pods
  pod "※ikemen", :path => "../"
end

target :ios do
  platform :ios, '8.0'
  link_with 'ikemen_Example'
  import_pods
end

target :iostests do
  platform :ios, '8.0'
  link_with 'ikemen_Tests'
  import_pods
  pod 'Quick'
  pod 'Nimble'
end

target :osx do
  platform :osx, '10.11'
  link_with 'ikemen-Example-osx'
  import_pods
end

